services:
  mysql:
    image: mysql:8.0
    container_name: api_nest_mysql
    restart: unless-stopped
    ports:
      - '3307:3306'
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: api_nest
      MYSQL_USER: nest
      MYSQL_PASSWORD: nest
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ['CMD', 'mysqladmin', 'ping', '-h', 'localhost', '-uroot', '-proot']
      interval: 5s
      timeout: 5s
      retries: 10

volumes:
  mysql_data:
